# Generated by Django 3.2.20 on 2023-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_date_of_wedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='partners_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='wedding_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='wedding_theme',
            field=models.CharField(blank=True, help_text='Let us know your theme so we can you find             the perfect gown to suit! E.g. rustic, winter, art deco', max_length=200, null=True),
        ),
    ]
