# Generated by Django 3.2.20 on 2023-08-05 11:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', cloudinary.models.CloudinaryField(default='placeholderCategory', max_length=255, verbose_name='image')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
