# Generated by Django 3.2.20 on 2023-08-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_on',
        ),
    ]
