# Generated by Django 3.2.20 on 2023-08-05 11:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', cloudinary.models.CloudinaryField(default='placeholderProduct', max_length=255, verbose_name='image')),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, default='Contact us to find out more about this gown', max_length=2000)),
                ('colours', models.TextField(blank=True, default='Ivory', max_length=500)),
                ('sizes_avail', models.TextField(blank=True, default='8 - 26', max_length=500)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('likes', models.ManyToManyField(related_name='fav_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
