# Generated by Django 3.2.20 on 2023-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='second_line_address',
            field=models.CharField(default='Enter second line of address', max_length=200),
        ),
    ]
