# Generated by Django 3.2.20 on 2023-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20230919_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='opening_times',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
