# Generated by Django 3.2.20 on 2023-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactdetail_opening_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetail',
            name='opening_times',
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='friday_opening_hrs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='monday_opening_hrs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='saturday_opening_hrs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='sunday_opening_hrs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='thursday_opening_hrs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='tuesday_opening_hrs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='wednesday_opening_hrs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
