# Generated by Django 3.2.20 on 2023-09-18 06:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=datetime.datetime.today)),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('11:30', '11:30'), ('14:00', '14:00'), ('16:30', '16:30')], help_text='All appointments are allocated 2 hours', max_length=20)),
                ('date_of_wedding', models.DateField(default=datetime.datetime.today)),
                ('no_in_party', models.PositiveSmallIntegerField(help_text='Please note max number of additional guests is 5', validators=[django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
