# Generated by Django 3.2.20 on 2023-09-17 14:44

import appointment.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime.today, validators=[appointment.models.Appointment.validate_date]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_of_wedding',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='no_in_party',
            field=models.PositiveSmallIntegerField(help_text='Please note max number of additional guests is 5', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00'), ('11:30', '11:30'), ('14:00', '14:00'), ('16:30', '16:30')], help_text='All appointments are allocated 2 hours', max_length=20),
        ),
    ]
