# Generated by Django 3.2.20 on 2023-09-18 13:15

import appointment.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(default=datetime.datetime.today, validators=[appointment.models.Appointment.validate_weekday]),
        ),
    ]
