# Generated by Django 3.2.20 on 2023-09-18 14:56

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(validators=[appointment.models.Appointment.validate_weekday]),
        ),
    ]
