# Generated by Django 3.2.20 on 2023-09-19 08:20

import appointment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0003_alter_appointment_booking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['booking_date']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(validators=[appointment.models.Appointment.validate_weekday, appointment.models.Appointment.validate_future_date]),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('user', 'booking_date', 'time')},
        ),
    ]
