# Generated by Django 3.2.20 on 2023-08-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_recommendation', models.CharField(choices=[('Music', 'Music'), ('Vehicles', 'Vehicles'), ('Venues', 'Venues'), ('Photographers', 'Photographers'), ('Photobooths', 'Photobooths'), ('Decor', 'Decor'), ('Bridesmaid dresses', 'Bridesmaid dresses'), ('Accesories', 'Accesories'), ('Catering', 'Catering')], max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('location', models.CharField(help_text='Please state the city or town', max_length=50)),
                ('link', models.URLField()),
                ('summary', models.TextField(help_text="Tell us a bit about why you're recommending this service", max_length=500)),
                ('date_posted', models.DateField(auto_now=True)),
                ('posted_by', models.CharField(default='{{ user.first_name }}', help_text='Enter your name, a username, or anonymous', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
