# Generated by Django 3.2.20 on 2023-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='link',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='web_link',
            field=models.TextField(default='www.google.com', max_length=2000),
        ),
    ]
