# Generated by Django 3.2.20 on 2023-08-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20230823_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='posted_by',
            field=models.CharField(help_text='Enter your name, a username, or anonymous', max_length=50),
        ),
    ]
