# Generated by Django 3.2.20 on 2023-08-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendation_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='type_of_recommendation',
            field=models.CharField(choices=[('Music', 'Music'), ('Vehicles', 'Vehicles'), ('Venues', 'Venues'), ('Photographers', 'Photographers'), ('Photobooths', 'Photobooths'), ('Decor', 'Decor'), ('Bridesmaid dresses', 'Bridesmaid dresses'), ('Accessories', 'Accessories'), ('Catering', 'Catering')], max_length=100),
        ),
    ]
