# Generated by Django 3.2.20 on 2023-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_recommendation_policy_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='policy_agree',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='decleration_of_consent',
            field=models.BooleanField(default=False, help_text='By ticking this box I agree to abide by the Code of Conduct'),
        ),
    ]
