# Generated by Django 3.2.20 on 2023-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_auto_20230828_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='decleration_of_consent',
            field=models.BooleanField(default=False, help_text='By ticking this box I agree to the below Code of Conduct'),
        ),
    ]
