# Generated by Django 3.2.20 on 2023-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_alter_recommendation_decleration_of_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='summary',
            field=models.TextField(help_text="Tell us a bit about why you're recommending this service", max_length=400),
        ),
    ]
