# Generated by Django 3.2.20 on 2023-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_alter_recommendation_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='summary',
            field=models.TextField(help_text="Tell us a bit about why you're recommending this service", max_length=250),
        ),
    ]
